# Generated by Django 3.2.16 on 2025-03-04 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_comment_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='post_id',
        ),
    ]
