# Generated by Django 3.2.16 on 2025-03-13 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
